//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Factory_occupation { get; set; }
        public string Country { get; set; }
        public string Buissnes_Priority { get; set; }
        public string Note { get; set; }
    }
}
