//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expends
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expends()
        {
            this.Total_Expends = new HashSet<Total_Expends>();
        }
    
        public int Id { get; set; }
        public string electrical_power { get; set; }
        public string water_expend { get; set; }
        public string workers_bonuses { get; set; }
        public string constant_expends { get; set; }
        public string buissness_expends { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Total_Expends> Total_Expends { get; set; }
    }
}
