//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Details
    {
        public int Id { get; set; }
        public string quantity_items { get; set; }
        public System.DateTime providing_date { get; set; }
        public int provided_product_id { get; set; }
        public int provider_name_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual Provided_Product Provided_Product { get; set; }
        public virtual Provider_Name Provider_Name { get; set; }
    }
}
