//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total_Expends
    {
        public int Id { get; set; }
        public int expends_type { get; set; }
        public string note { get; set; }
        public string date { get; set; }
        public int value { get; set; }
    
        public virtual Expends Expends { get; set; }
    }
}
